language: node_js

node_js:
- "0.10"
- "0.12"
- "5"

sudo: false

cache:
  directories:
  - $HOME/.ccache
  - apt: true

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - libstdc++6 # upgrade libstdc++ on linux to support C++11


after_success:
 - if [[ $(uname -s) == 'Linux' ]]; then
        ldd node_modules/zipfile/lib/*/*/*node;
   fi